# Generated by Django 3.1.4 on 2021-01-16 09:00

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ahinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='ahi/item/'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ahinventory.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='storelocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ahinventory.storagelocation'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='prefix',
            field=models.CharField(max_length=50),
        ),
    ]
